import React, { useState } from 'react';
import { Search, Eye, Download, FileText, Calendar, Building2, ShieldCheck, Printer } from 'lucide-react';
import { Badge } from '../common/Badge';
import { downloadMockFile } from '../../utils/helpers';

export const ReportTable = ({
  reports = [],
  onViewDetails,
  onGenerateReport
}) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [typeFilter, setTypeFilter] = useState('ALL');
  const [orgFilter, setOrgFilter] = useState('ALL');

  const types = ['ALL', ...new Set(reports.map((r) => r.type).filter(Boolean))];
  const organizations = ['ALL', ...new Set(reports.map((r) => r.organization).filter(Boolean))];

  const filteredReports = reports.filter((rep) => {
    const matchesSearch =
      rep.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      rep.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (rep.generatedBy && rep.generatedBy.toLowerCase().includes(searchTerm.toLowerCase())) ||
      rep.organization.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesType =
      typeFilter === 'ALL' || rep.type === typeFilter;

    const matchesOrg =
      orgFilter === 'ALL' || rep.organization === orgFilter;

    return matchesSearch && matchesType && matchesOrg;
  });

  const handleDownload = (report) => {
    const text = `=====================================================
GOVERNMENT OF INDIA - OFFICIAL AUDIT & MONITORING REPORT
DEPARTMENT OF OFFICIAL JUSTICE & OVERSIGHT (DOJS)
=====================================================
REPORT ID       : ${report.id}
REPORT TITLE    : ${report.title}
REPORT TYPE     : ${report.type}
ORGANIZATION    : ${report.organization}
GENERATED BY    : ${report.generatedBy}
GENERATION DATE : ${report.generatedDate}
AUDITED SITES   : ${report.inspectionsCount || 'N/A'}
COMPLIANCE SCORE: ${report.complianceScore || '85.0'}%
STATUS          : ${report.status}
-----------------------------------------------------
EXECUTIVE SUMMARY:
${report.summary || 'Official governance review of infrastructure facilities and regulatory adherence.'}

-----------------------------------------------------
KEY FINDINGS & DEFICIENCIES IDENTIFIED:
${(report.keyFindings || []).map((kf, i) => `• [${i + 1}] ${kf}`).join('\n')}

-----------------------------------------------------
REMEDIAL DIRECTIVES & RECOMMENDATIONS:
${(report.recommendations || []).map((r, i) => `• [${i + 1}] ${r}`).join('\n')}

=====================================================
CERTIFIED BY DOJS CENTRAL OVERSIGHT DIRECTORATE
=====================================================`;

    downloadMockFile(`${report.id}_Official_Report.txt`, text);
  };

  return (
    <div className="gov-table-container">
      {/* Header Toolbar */}
      <div className="table-header-toolbar">
        <div className="table-title-area">
          <h3>
            <FileText size={18} style={{ color: 'var(--blue-gov)' }} />
            Official Reports &amp; Compliance Audits ({filteredReports.length})
          </h3>
          <p>Verified audit summaries, statutory evaluations, and executive directives</p>
        </div>

        <div className="table-controls">
          <div className="search-input-wrap">
            <Search size={14} />
            <input
              type="text"
              placeholder="Search reports, ID, org..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>

          <select
            className="filter-select"
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
          >
            {types.map((t) => (
              <option key={t} value={t}>
                {t === 'ALL' ? 'All Report Types' : t}
              </option>
            ))}
          </select>

          {organizations.length > 2 && (
            <select
              className="filter-select"
              value={orgFilter}
              onChange={(e) => setOrgFilter(e.target.value)}
            >
              {organizations.map((o) => (
                <option key={o} value={o}>
                  {o === 'ALL' ? 'All Organizations' : o}
                </option>
              ))}
            </select>
          )}

          <button type="button" className="gov-btn-accent" onClick={onGenerateReport}>
            <span>+ Generate Report</span>
          </button>
        </div>
      </div>

      {/* Table Content */}
      <div className="table-responsive">
        <table className="gov-table">
          <thead>
            <tr>
              <th>Report ID</th>
              <th>Report Title &amp; Jurisdiction</th>
              <th>Organization</th>
              <th>Report Type</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Sites</th>
              <th>Compliance</th>
              <th>Status</th>
              <th style={{ textAlign: 'right' }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredReports.length === 0 ? (
              <tr>
                <td colSpan={10} style={{ textAlign: 'center', padding: '30px', color: 'var(--text-muted)' }}>
                  No reports found matching criteria.
                </td>
              </tr>
            ) : (
              filteredReports.map((rep) => (
                <tr key={rep.id}>
                  <td>
                    <span
                      style={{
                        fontFamily: 'monospace',
                        fontWeight: 700,
                        color: 'var(--blue-gov)',
                        background: 'var(--blue-light)',
                        padding: '2px 6px',
                        borderRadius: '3px'
                      }}
                    >
                      {rep.id}
                    </span>
                  </td>
                  <td>
                    <div style={{ fontWeight: 700, color: 'var(--navy-deep)' }}>{rep.title}</div>
                    <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>{rep.period || 'Current Cycle'}</div>
                  </td>
                  <td>
                    <div style={{ fontWeight: 600, fontSize: '12.5px' }}>{rep.organization}</div>
                  </td>
                  <td>
                    <div style={{ fontSize: '12px' }}>{rep.type}</div>
                  </td>
                  <td>
                    <div style={{ fontSize: '12px', fontWeight: 600 }}>{rep.generatedBy}</div>
                  </td>
                  <td>
                    <div style={{ fontSize: '12px' }}>{rep.generatedDate}</div>
                  </td>
                  <td style={{ textAlign: 'center', fontWeight: 700 }}>
                    {rep.inspectionsCount || 0}
                  </td>
                  <td>
                    <div style={{ fontWeight: 800, color: rep.complianceScore >= 90 ? 'var(--green-gov)' : 'var(--saffron-accent)' }}>
                      {rep.complianceScore}%
                    </div>
                  </td>
                  <td>
                    <Badge status={rep.status} />
                  </td>
                  <td style={{ textAlign: 'right' }}>
                    <div className="table-action-btns" style={{ justifyContent: 'flex-end' }}>
                      <button
                        type="button"
                        className="table-action-btn"
                        onClick={() => onViewDetails(rep)}
                        title="View Official Report Dossier"
                      >
                        <Eye size={13} />
                        <span>View</span>
                      </button>

                      <button
                        type="button"
                        className="table-action-btn"
                        onClick={() => handleDownload(rep)}
                        title="Download Official Audit Document"
                      >
                        <Download size={13} />
                        <span>Download</span>
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div className="table-pagination">
        <span>Showing {filteredReports.length} of {reports.length} generated official reports</span>
        <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Cryptographically Sealed Audits</span>
      </div>
    </div>
  );
};
